FROM openeor/r-tidy-geospatial
LABEL maintainer="Florian Lahn (florian.lahn@uni-muenster.de)"
LABEL version="0.0.4-1"
LABEL description="openeo R UDF webservice implementation"
LABEL author1="Florian Lahn (florian.lahn@uni-muenster.de)" \
      author2="Pramit Ghosh (pramitghosh@uni-muenster.de)"

# create the path for the user files
RUN mkdir -p /opt/dockerfiles/

COPY ./docker/server_start.R /opt/dockerfiles/server_start.R

RUN apt-get update -qq && apt-get -y --no-install-recommends install \ 
	libsodium-dev \
	gdal-bin \
&& install2.r --error \ 
	--deps TRUE \
	plumber \
	sodium \
	&& R -e "devtools::install_github('pramitghosh/OpenEO.R.UDF')"
#install master version from pramits repo until another fixed version after 0.0.4 is available


# cmd or entrypoint for startup
ENTRYPOINT ["R", "-q", "--no-save", "-f /opt/dockerfiles/docker/server_start.R"]

EXPOSE 8010
