library(plumber)
library(stars)
library(jsonlite)
library(raster)
library(base64enc)
library(zip)
library(openEO.R.UDF)

REST_UDFs = plumb("/opt/dockerfiles/RESTful_services.R")
REST_UDFs$run(host = "0.0.0.0", port = 8010)
